name: admin-ui-funckey
namespace: official
version: 0.0.2-3
author: Wazo Team
display_name: Funckey
min_wazo_version: 18.02
tags:
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-funckey
