name: admin-ui-funckey
namespace: official
version: 0.0.2-4
author: Wazo Team
display_name: Function Keys
min_wazo_version: 18.02
tags:
  - application
  - funckey
homepage: https://github.com/wazo-pbx/wazo-admin-ui-funckey
icon: th-list
